# Generated by Django 2.2.6 on 2019-10-06 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='build',
            name='finished_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='build',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
