# Generated by Django 2.2.6 on 2019-10-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20191006_0911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='build',
            name='result',
            field=models.PositiveSmallIntegerField(choices=[(1, 'SUCCESS'), (2, 'FAILURE'), (3, 'RUNNING'), (4, 'PENDING')], default=4),
        ),
    ]
